### ISSUE TITLE
Tasks appear in workflow but not in To Do

### ISSUE THREAD

**Issue by naimfrewat** [johandebeurs/alfred-mstodo-workflow#13]
Hello,
It's possible to create tasks from within the workflow but those are not synced to the applications (macos & android).
Changing the default folder (or even confirming it) yields the below error
![image](https://user-images.githubusercontent.com/69073360/89098056-e0792600-d3ec-11ea-9b44-cce2b54a05c2.png)

Thanx,
Naim

**Comment by johandebeurs** [comment]
This is resolved in https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.1.3
