### ISSUE TITLE
Cannot change the default folder

### ISSUE THREAD

**Issue by pedrofernandezm** [johandebeurs/alfred-mstodo-workflow#14]
## Expected Behavior
- I type in Alfred `td-pref default_folder Work` to select my `Work` list as the default list.
- The list is set as default.
- The next task is created inside the Work list.

## Current Behavior
- I type in Alfred `td-pref default_folder Work` to select my `Work` list as the default list.
- And error is displayed.
![Screen Shot 2020-08-11 at 4 22 26 PM](https://user-images.githubusercontent.com/132822/89950499-58b2c900-dbef-11ea-8b48-ec5cfe852c86.png)
- The next task is created in a different list.

## Context (Environment)
- Workflow version installed: 0.1.2
- Microsoft To Do version:  2.23 (200716.1536)

**Comment by manavortex** [comment]
+1, experiencing the same issue! I'd love a fix

**Comment by johandebeurs** [comment]
Sorry for delay - should be resolved in [release 0.1.3](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.1.3), please test and confirm

**Comment by manavortex** [comment]
works, thank you! <3
