### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by arnaudlamy** [johandebeurs/alfred-mstodo-workflow#19]
Hi,

It worked few days and now impossible to create a task. I tried to remove / reinstall but nothing (maybe an auth issue). How I can reset everything even auth, cache and config?

Thanks

**Comment by smnkrt** [comment]
Any updates on this?
i've run into the same issue recently after Big Sur update, i tried reinstalling, but no luck. 
in logs i found: 

```
The domain/default pair of (kCFPreferencesAnyApplication, AppleLocale) does not exist
```
and 
```
PasswordNotFound
```
Any tips/tricks for this @johandebeurs?

**Comment by johandebeurs** [comment]
I'm also on a fresh install on Big Sur and am not seeing any issues on my side. Can you:
- try running `_td-full-reset` from alfred. This should clear everything out, but double check the following
- check apple keychain for any application passwords with `com.johandebeurs.alfred.mstodo` names. Remove these if they exist
- (optional) check the contents of ~/Library/Application Support/Alfred/Workflow Data/com.johandebeurs.alfred.mstodo. You can brute force delete the mstodo.db sqlite database to remove the cached tasks if there is a sync conflict
- try re-authorising the application

**Comment by johandebeurs** [comment]
Auth has been reworked in [release 0.2.0](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.2.0) which should resolve these issues
