### ISSUE TITLE
can not complete authorization

### ISSUE THREAD

**Issue by layae** [johandebeurs/alfred-mstodo-workflow#20]
Can not complete the authorization, but it shows like below:
http://127.0.0.1:5000/?code=0.AAAAM1J11q9GMECJBgV70pqe6K_l8yeELXNAkfqTkCCNFScPAEA.AQABAAIAAAB2UyzwtQEKR7-rWbgdcBZIkaoV6qr2sNnZmIZdbJjUFduzX8oMk0pdBqoGMdSpxtz8eHM6cwSdtb8XScU5gsJFiWK0glooAwBGusXpKhy6HZlAbw5m-iT7mqmeiX8cpk2haeYOfiOOBZMp-kvp9OpceE_aM-jPmKBFf71LrtzmYhKLQ5zNBOYpTk1G_4kzoDfS_I8HLuSLCenDYOe5k4Njf3UI0Vx8kzOA0ckmyOuun_H2jJEG-MqUdB75RH37NhKKHc_LGVmTV92f4WLGS9kVlcaLukPH183sRYNc6hNpm3H6S-7iQjB3qtletPkB8mpkLmFhZ1I0PXKkIK3hmB1HNUrMN4wcZ3FZuLGYXAnr1PD0qDIxWQsIlK2v4aWN43ME68wTHPwYMEakKGfS8Vygi0kaQYgESNtRqMRmVIWhM0Zxyuwdu_GyeiWXGFEdwM1JIAe8nc_R4KZgN6O4WI1iwrRk3RBk6F2poRKI3SaQ9oW2dfLUtVEC-sF3FR9m3jyfBdo-OV89cE2r1PUmZdPulDIIyuSJBfMJZorWabP_6pgx8m-xvsm3Qx7BECWkZmMxaRtlGjCyQZUSs8w2D9HA0X4fNZ24-6qW98n8wPowmYhZEPkk48yD80yZQFEvBMwARzZ1wu2mZvvRn6LK5R4jegkWzTWNB8eawYdU9-0FKSAA&state=0FTQJJYSY25M9DGJB2RK&session_state=69f6b945-7eb2-4b41-ae27-ce5822bc7c5a

I've tried several ways to overcome this problem, but I still don't know what is wrong.
Please let me know how to fix it.

thanks

**Comment by johandebeurs** [comment]
The application should redirect to a URL like this on successful auth and show you a `You are now logged in` message in the browser. Is this not the case for you?

**Comment by h-jia** [comment]
Same here

**Comment by ramseylove** [comment]
I received the error and workflow is unable to connect to MS account. When I try to use the workflow it brings me back through the Microsoft login process, and then fails to redirect to a url like this. 

http://127.0.0.1:5000/?code=M.R3_BAY.fd631f82-5e40-d775-cc29-14a8dcd9d709&state=REA3A9EVMT7S6HWXJF86

 My Microsoft account is a personal account and setup with 2FA. I'm on Mac OS 11.3.1 - Alfred 4.5.1

**Comment by a-rock-lobster** [comment]
I too have started having this problem. Had to do a clean install of osx and now I cannot get the workflow running again.
edit: I can see that the workflow has been given permission in my microsoft account. I removed and tried the workflow setup again. The workflow was added again as an app with permissions in my ms account but still to no avail as the same result occurs.

**Comment by a-rock-lobster** [comment]
So, just managed to get working. 
Two things (not sure which, if either, helped). 1) I emptied the trash after deleting the workflow. 2) I downloaded from 
https://www.packal.org/workflow/microsoft-todo
as opposed to the link on the github page. No idea if/how they are different.

**Comment by h-jia** [comment]
@a-rock-lobster huuuu.. The packal link works like a charm!

**Comment by razhangwei** [comment]
> So, just managed to get working. Two things (not sure which, if either, helped). 1) I emptied the trash after deleting the workflow. 2) I downloaded from https://www.packal.org/workflow/microsoft-todo as opposed to the link on the github page. No idea if/how they are different.

The one downloaded from packal worked for me as well!! I noticed that it is actually of version 1.21, in contrast to version 1.3 for the one downloaded from the repo page. Does it indicate that there is some bug introduced in v1.3?

**Comment by freedomlang** [comment]
@layae AirPlay Receiver has used that address in macOS Monterey, Close that may help

**Comment by folef** [comment]
I am having the same issues. Not sure but shutting down AirPlay with macOS Monterey looks like not possible anymore... Any idea?

Edit: also pasting the url in the [Having Troubles] menu isn't working unfortunately

**Comment by johandebeurs** [comment]
Auth has been refactored in [release 0.2.0](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.2.0) which should resolve these issues
