### ISSUE TITLE
After successfull connection Alfred TODO shows errors (company account) 

### ISSUE THREAD

**Issue by tmerten** [johandebeurs/alfred-mstodo-workflow#25]
Hi there,

I just tried to connect the alfred-mstodo-workflow to my (company) account. The connection worked out well (redirect and all) and I can add tasks to my personal task list.

But whenever I try anything else I receive the following error `Error in workflow 'Microsoft ToDo' UNIQUE constraint failed: task.id`

![image](https://user-images.githubusercontent.com/3410703/109973789-1c64c880-7cf9-11eb-90c8-3c36688a76f8.png)

Without knowing much about the app and/or the MS API I think it might be due to the company account. Maybe group tasks use the same ID as personal tasks and thus the ID needs to be some kind of combined key (e.g. `list name + ID`). Anyways, I am happy to help debug this if you tell me how to provide information.

Cheers
Thorsten

**Comment by johandebeurs** [comment]
This sounds like a sync error with the local sqlite db. Can you remove the mstodo.db database from ~/Library/Application Support/Alfred/Workflow Data/com.johandebeurs.alfred.mstodo and then try again? It should auto-sync but if not you can try to force a sync via `td-pref sync`. Drop the workflow debug output here if you get further errors when doing so
