### ISSUE TITLE
 Is the workflow dead in MacOS 12.3?

### ISSUE THREAD

**Issue by ghost** [johandebeurs/alfred-mstodo-workflow#36]
I am getting a python error that I'm guessing has to do with Python 2.7 being removed in 12.3. Is this very useful workflow not usable in 12.3?

**Comment by browneye1826** [comment]
@johandebeurs Pretttty please , there are so many of us that will love you endlessly for fixing this! I spent a bunch of hours trying but I'm just not as good as you...

**Comment by a-rock-lobster** [comment]
You can install a temporary fix (until this workflow gets updated to Python 3) here:
https://github.com/alfredapp/updated-third-party-python2-workflows

It requires you first reinstall python 2, which you can do here:
https://www.alfredapp.com/help/kb/python-2-monterey/

**Comment by browneye1826** [comment]
Thanks so much @a-rock-lobster, I'll give it a try.

**Comment by johandebeurs** [comment]
Ack - have just started on a Py3 refactor, but it may take me a while to complete. The difference in our coding skills may not be as much as you think 😅

**Comment by johandebeurs** [comment]
This is resolved in [release 0.2.0](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.2.0)
