### ISSUE TITLE
Not working with Python3

### ISSUE THREAD

**Issue by y-lakhdar** [johandebeurs/alfred-mstodo-workflow#44]
When running the workflow, I get the following error:
```
ModuleNotFoundError: No module named 'cPickle'
```
I do not have python2 installed by default in my M1 chip and there is no information on how to run the workflow with Python3.

**Comment by johandebeurs** [comment]
Have just started working on a broad refactor to Py3 and addressing a bunch of security issues. No ETA for re-release but things will be broken until I complete this, so please bear with me here

**Comment by HaloTT** [comment]
Looking forward to supporting py3

**Comment by johandebeurs** [comment]
This is resolved in [release 0.2.0](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.2.0)
