### ISSUE TITLE
getting "We're unable to complete your request" when trying to log in

### ISSUE THREAD

**Issue by mdonato-fn** [johandebeurs/alfred-mstodo-workflow#48]
Alfred and MS ToDo are updated to the latest version. When trying to launch the workflow, I get a page with the above, and:

`invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.`

I am not sure what happened, I did not use it for a month or so and now I get this

**Comment by johandebeurs** [comment]
In the middle of a refactor so unfortunately made some breaking changes. Hoping to have another version published in a few days

**Comment by mdonato-fn** [comment]
Thanks for letting me know!

**Comment by johandebeurs** [comment]
This is resolved in [release 0.2.0](https://github.com/johandebeurs/alfred-mstodo-workflow/releases/tag/0.2.0)

**Comment by mdonato-fn** [comment]
Thanks @johandebeurs !
