### ISSUE TITLE
Can't complete authorization of Microsoft account

### ISSUE THREAD

**Issue by ghost** [johandebeurs/alfred-mstodo-workflow#6]
Note: I am using Alfred 4.

With the latest version, I am seeing the setup options in Alfred, but after I click on "Please log in" and sign into Microsoft, I get an error message in Safari. It is trying to open this URL:

http://127.0.0.1:5000/?code=0.AQgAu76M3Tkh-E20EU4-h6vrXK_l8yeELXNAkfqTkCCNFScIAG4.AQABAAIAAAAm-06blBE1TpVMil8KPQ41EnDQCDyarC_e4V1Fc832aOxaTsh7sT371pPMGhDA1F2RKYvzGEbicmsGhnyb26S3UcpSofDd9eGrl8xxQ0-OmMTJGxfqzujA4XYJSPv278Wz-exJ6aql3jmbWsmpPxSJtYj-xe4jDrJTRZUceRErKR0xqC55Qmv4SETTu25KdImc7nHvP4rABvlm6rAqwNQROxuRTOjWX5DfOS1UCBE3zdgsV_r3WeJhb8TOUae4fWmRWxe-cKbkkKdr_qssmaDJFFDJxmMZjuupOn_leykTH955QwlVVUjhAFD4GfV34VX9VfjPs08ABt5LXtzWrfEe_8BJ9fITVKHC5n0Rw393iFDsyeFgOqxVoSecwJuxrn1lgLF_Ktmib-kD7UCkPV3-2FlTf4FUmAphq_T3nHUWVdDZ5CTx8icm0mB1v_Nib-MlYcUeaBLY_wr7QsIo6lnXxmPVwhNx-H5GaScoTJ6J8nmABstUrzrTN5MqxR6Gj7U6YVykZdu57tnqYRwscmkdZ30ejm0QpRMd6okXxL1i1DlathJJeE90iL_M-dk-AWnraWohHomoQYBo8ZU7kMtNjBPcnOXKpcjA03lwSDoCM2VoDwPtgjLPpoKJv-w-iK4gAA&state=PYWVWEWJARL8F1JSY36S&session_state=eec1b180-e97d-4f10-940c-44eda325a665

**Comment by koboyer** [comment]
Same here - Alfred notifies that an exception occurred. It does seem that when I when through there "log in" command in Alfred, and logged into my account - that outlook did give access to teh Alfred app. But when I try to use the workflow it keeps asking me to log in

**Comment by johandebeurs** [comment]
Thanks. Can you post details shown in the debug screen in the workflow preferences? If you go into MacOS keychain and search for "Alfred.mstodo", what do you see stored?

**Comment by johandebeurs** [comment]
Hypothesis on this is that the data folder (ie ~/Library/Application Support/Alfred 3/Workflow Data/com.johandebeurs.alfred.mstodo)
is different in Alfred4 (ie ~/Library/Application Support/Alfred/Workflow Data/com.johandebeurs.alfred.mstodo)

Not sure on a solution yet as I don't understand how to handle the versioning but I will hunt down a solution. Please feel free to propose a PR if you find a fix

**Comment by ghost** [comment]
Here is what I get in the debug screen:

[05:27:12.514] Logging Started…
[05:27:18.463] Microsoft ToDo[Script Filter] Queuing argument ‘’
[05:27:18.795] Microsoft ToDo[Script Filter] Script with argv ‘(null)’ finished
[05:27:18.799] STDERR: Microsoft ToDo[Script Filter] .
2020-05-10 05:27:18,714 root         DEBUG    loading cached data: /Users/benmattison/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.johandebeurs.alfred.mstodo/__workflow_latest_version.cpickle
2020-05-10 05:27:18,715 mstodo       INFO     Workflow response complete
2020-05-10 05:27:18,715 workflow     DEBUG    set last run version: 0.1.2
2020-05-10 05:27:18,715 workflow     DEBUG    ––––– finished in 0.038s –––––
[05:27:18.801] Microsoft ToDo[Script Filter] <?xml version=”1.0” encoding=”utf-8”?>
<items><item valid=”yes”><title>Please log in</title><subtitle>Authorise Alfred ToDo Workflow to use your Microsoft account</subtitle><icon>icons/dark/account.png</icon></item><item autocomplete=”-help “ valid=”no”><title>Having trouble?</title><subtitle /><icon>icons/dark/help.png</icon></item><item autocomplete=”-about “ valid=”no”><title>About</title><subtitle>Learn about the workflow and get support</subtitle><icon>icons/dark/info.png</icon></item></items>
[05:27:20.996] Microsoft ToDo[Script Filter] Processing complete
[05:27:20.999] Microsoft ToDo[Script Filter] Passing output ‘’ to Run Script
[05:27:21.788] STDERR: Microsoft ToDo[Run Script] .
Process Process-1:
Traceback (most recent call last):
  File “/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py”, line 267, in _bootstrap
    self.run()
  File “/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py”, line 114, in run
    self._target(*self._args, **self._kwargs)
  File “/Users/benmattison/Documents/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FD2E812E-1426-41F1-8E32-FC4A6CDC92BF/mstodo/auth.py”, line 144, in await_token
    from http.server import HTTPServer, SimpleHTTPRequestHandler
ImportError: No module named http.server
2020-05-10 05:27:21,704 mstodo       INFO     Workflow response complete
[05:27:21.802] Microsoft ToDo[Run Script] Processing complete
[05:27:21.803] Microsoft ToDo[Run Script] Passing output ‘’ to Post Notification

**Comment by ghost** [comment]
And here is what I see in the keychain. There is a password if I check "Show Password."
<img width="534" alt="Screen Shot 2020-05-10 at 5 30 59 AM" src="https://user-images.githubusercontent.com/64958121/81495642-c281a680-927f-11ea-8399-ef402934cfb5.png">
<img width="537" alt="Screen Shot 2020-05-10 at 5 30 53 AM" src="https://user-images.githubusercontent.com/64958121/81495644-c4e40080-927f-11ea-9133-e1b3a8059eaf.png">

**Comment by johandebeurs** [comment]
OK, interesting. failing to start local server to catch the response. Thanks for the screens, will take another stab. Likely something to do with the py environment / packages bundled with the workflow

**Comment by johandebeurs** [comment]
Can you test again? switched to different package import structure which should resolve

**Comment by ghost** [comment]
Installed again and it worked perfectly! Thanks so much, this is going to be a big part of my daily work life.

**Comment by h-jia** [comment]
Same here

**Comment by ghost** [comment]
@h-jia I have been able to solve login problems by deleting the "com.johandebeurs.alfred.mstodo" Keychain items.

**Comment by h-jia** [comment]
@ben428 Thanks. Unfortunately, it is still not working after delete the mstodo keychain, reboot the system and reinstall the workflow. It says:[http://127.0.0.1:5000/?code=M.R3_BAY.0654073a-a92e-4b25-c12f-9fc746d20cf9&state=4F4MWMKC6V4VTUU79PUT...]( http://127.0.0.1:5000/?code=M.R3_BAY.0654073a-a92e-4b25-c12f-9fc746d20cf9&state=4F4MWMKC6V4VTUU79PUT...)
