### ISSUE TITLE
Doesn't support add task to default task lists?

### ISSUE THREAD

**Issue by polyzy** [johandebeurs/alfred-mstodo-workflow#9]
I find it doesn't work when I add todos in my list which is named by Chinese. And mstodo can not support to change default language.

**Comment by johandebeurs** [comment]
To clarify:
- you have existing lists which have Chinese character titles
- you can log in and synchronise your tasks in the workfow
- you cannot add tasks to one of these lists which have Chinese character titles

Some questions
- Are your existing tasks and lists displayed correctly?
- Is there any other functionality which is problematic (eg searching lists, displaying due/upcoming lists)?
- Can you provide a screenshot of the error messages in the debug window if any?

**Comment by polyzy** [comment]
Sorry I didn't make myself clear.

Screenshot:
![image](https://user-images.githubusercontent.com/7263718/81884631-f257e380-95ca-11ea-99e2-4b62598a6ebc.png)

I tried to add task to the **default list** called "我的一天"( means 'My Day' in English). The command is "td 我的一天: test task in my day". Actually this task was not displayed in "我的一天" but in "任务"(means "Task" in English). "任务" is another default list as you can see in  the screenshot above. The default list cannot be deleted and renamed.

I also test in the list which is  **created by myself** called "中文测试", and enter command like "td 中文测试: test test". Then I found it works.

**Comment by johandebeurs** [comment]
OK, understood. "My day" is not a list itself but an abstraction outside of that which can contain tasks from multiple lists, and unfortunately access to this isn't available via the Microsoft Graph API (https://docs.microsoft.com/en-us/graph/api/resources/outlooktask?view=graph-rest-beta) which this is built on. If they ever update the API I'll look to include this functionality

**Comment by polyzy** [comment]
Got it. I think it't better to explain this in `README.md`. 
Thanks for your answer.
